import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import 'bootstrap/dist/css/bootstrap.min.css';
import { ReactNode } from 'react';
import ImportBsJS from '@/components/ImportBootstrapJS';
import Navbar from '@/components/Navbar';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Book Catalog',
  description: 'Generated by create next app',
};

type Props = {
  children: ReactNode;
};

function RootLayout({ children }: Props) {
  return (
    <html lang="en" data-bs-theme="dark">
      <body className={inter.className}>
        <ImportBsJS />
        <Navbar />
        <div className="container">{children}</div>
      </body>
    </html>
  );
}

export default RootLayout;
